#!/bin/bash

echo "🔧 Quick Fix for Clerk Session Mismatch"
echo ""
echo "The issue: Browser has cached session from keen-octopus-70"
echo "Solution: Clear browser storage and sign in again"
echo ""
echo "Steps:"
echo "1. Open browser DevTools (F12)"
echo "2. Go to Application tab → Storage"
echo "3. Click 'Clear site data' for localhost:3001"
echo "4. Close and reopen the browser tab"
echo "5. Navigate to http://localhost:3001"
echo "6. Sign in again"
echo ""
echo "OR use incognito/private window for a fresh session"
echo ""
echo "After signing in, check backend logs for:"
echo "✅ token_issuer: https://real-pegasus-21.clerk.accounts.dev"
